name: Cypress Tests using Cypress Docker Image

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Upload Mocha Awesome Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mocha-awesome-report
          path: cypress/reports/html/index.html
