name: Cypress Tests using Cypress Docker Image

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build --no-cache -t cypress-tests .

      - name: Run Cypress Tests
        run: |
          docker run --rm -v ${{github.workspace}}:/app cypress-tests
